.PHONY: clean All

All:
	@echo "----------Building project:[ 06_1 - Debug ]----------"
	@cd "06_1" && $(MAKE) -f  "06_1.mk"
clean:
	@echo "----------Cleaning project:[ 06_1 - Debug ]----------"
	@cd "06_1" && $(MAKE) -f  "06_1.mk" clean
