.PHONY: clean All

All:
	@echo "----------Building project:[ 06_2 - Debug ]----------"
	@cd "06_2" && $(MAKE) -f  "06_2.mk"
clean:
	@echo "----------Cleaning project:[ 06_2 - Debug ]----------"
	@cd "06_2" && $(MAKE) -f  "06_2.mk" clean
