.PHONY: clean All

All:
	@echo "----------Building project:[ ex01_1 - Debug ]----------"
	@cd "ex01_1" && $(MAKE) -f  "ex01_1.mk"
clean:
	@echo "----------Cleaning project:[ ex01_1 - Debug ]----------"
	@cd "ex01_1" && $(MAKE) -f  "ex01_1.mk" clean
