.PHONY: clean All

All:
	@echo "----------Building project:[ ex01_2 - Debug ]----------"
	@cd "ex01_2" && $(MAKE) -f  "ex01_2.mk"
clean:
	@echo "----------Cleaning project:[ ex01_2 - Debug ]----------"
	@cd "ex01_2" && $(MAKE) -f  "ex01_2.mk" clean
