.PHONY: clean All

All:
	@echo "----------Building project:[ ex_07_1 - Debug ]----------"
	@cd "ex_07_1" && $(MAKE) -f  "ex_07_1.mk"
clean:
	@echo "----------Cleaning project:[ ex_07_1 - Debug ]----------"
	@cd "ex_07_1" && $(MAKE) -f  "ex_07_1.mk" clean
