.PHONY: clean All

All:
	@echo "----------Building project:[ ex3_1_teil2 - Debug ]----------"
	@cd "ex3_1_teil2" && $(MAKE) -f  "ex3_1_teil2.mk"
clean:
	@echo "----------Cleaning project:[ ex3_1_teil2 - Debug ]----------"
	@cd "ex3_1_teil2" && $(MAKE) -f  "ex3_1_teil2.mk" clean
