.PHONY: clean All

All:
	@echo "----------Building project:[ ex3_2 - Debug ]----------"
	@cd "ex3_2" && $(MAKE) -f  "ex3_2.mk"
clean:
	@echo "----------Cleaning project:[ ex3_2 - Debug ]----------"
	@cd "ex3_2" && $(MAKE) -f  "ex3_2.mk" clean
