.PHONY: clean All

All:
	@echo "----------Building project:[ decimaltobinary - Debug ]----------"
	@cd "decimaltobinary" && $(MAKE) -f  "decimaltobinary.mk"
clean:
	@echo "----------Cleaning project:[ decimaltobinary - Debug ]----------"
	@cd "decimaltobinary" && $(MAKE) -f  "decimaltobinary.mk" clean
