.PHONY: clean All

All:
	@echo "----------Building project:[ aufgabe3 - Debug ]----------"
	@cd "aufgabe3" && $(MAKE) -f  "aufgabe3.mk"
clean:
	@echo "----------Cleaning project:[ aufgabe3 - Debug ]----------"
	@cd "aufgabe3" && $(MAKE) -f  "aufgabe3.mk" clean
