.PHONY: clean All

All:
	@echo "----------Building project:[ 09_2 - Debug ]----------"
	@cd "09_2" && $(MAKE) -f  "09_2.mk"
clean:
	@echo "----------Cleaning project:[ 09_2 - Debug ]----------"
	@cd "09_2" && $(MAKE) -f  "09_2.mk" clean
