.PHONY: clean All

All:
	@echo "----------Building project:[ ex04_1_aufgabe1 - Debug ]----------"
	@cd "ex04_1_aufgabe1" && $(MAKE) -f  "ex04_1_aufgabe1.mk"
clean:
	@echo "----------Cleaning project:[ ex04_1_aufgabe1 - Debug ]----------"
	@cd "ex04_1_aufgabe1" && $(MAKE) -f  "ex04_1_aufgabe1.mk" clean
