.PHONY: clean All

All:
	@echo "----------Building project:[ ex04_1_aufgabe2 - Debug ]----------"
	@cd "ex04_1_aufgabe2" && $(MAKE) -f  "ex04_1_aufgabe2.mk"
clean:
	@echo "----------Cleaning project:[ ex04_1_aufgabe2 - Debug ]----------"
	@cd "ex04_1_aufgabe2" && $(MAKE) -f  "ex04_1_aufgabe2.mk" clean
