.PHONY: clean All

All:
	@echo "----------Building project:[ ex04_2 - Debug ]----------"
	@cd "ex04_2" && $(MAKE) -f  "ex04_2.mk"
clean:
	@echo "----------Cleaning project:[ ex04_2 - Debug ]----------"
	@cd "ex04_2" && $(MAKE) -f  "ex04_2.mk" clean
