.PHONY: clean All

All:
	@echo "----------Building project:[ ex10_1 - Debug ]----------"
	@cd "ex10_1" && $(MAKE) -f  "ex10_1.mk"
clean:
	@echo "----------Cleaning project:[ ex10_1 - Debug ]----------"
	@cd "ex10_1" && $(MAKE) -f  "ex10_1.mk" clean
