.PHONY: clean All

All:
	@echo "----------Building project:[ ex10_2 - Debug ]----------"
	@cd "ex10_2" && $(MAKE) -f  "ex10_2.mk"
clean:
	@echo "----------Cleaning project:[ ex10_2 - Debug ]----------"
	@cd "ex10_2" && $(MAKE) -f  "ex10_2.mk" clean
