.PHONY: clean All

All:
	@echo "----------Building project:[ aufgabe1 - Debug ]----------"
	@cd "aufgabe1" && $(MAKE) -f  "aufgabe1.mk"
clean:
	@echo "----------Cleaning project:[ aufgabe1 - Debug ]----------"
	@cd "aufgabe1" && $(MAKE) -f  "aufgabe1.mk" clean
