.PHONY: clean All

All:
	@echo "----------Building project:[ ex02_2 - Debug ]----------"
	@cd "ex02_2" && $(MAKE) -f  "ex02_2.mk"
clean:
	@echo "----------Cleaning project:[ ex02_2 - Debug ]----------"
	@cd "ex02_2" && $(MAKE) -f  "ex02_2.mk" clean
