.PHONY: clean All

All:
	@echo "----------Building project:[ frage2 - Debug ]----------"
	@cd "frage2" && $(MAKE) -f  "frage2.mk"
clean:
	@echo "----------Cleaning project:[ frage2 - Debug ]----------"
	@cd "frage2" && $(MAKE) -f  "frage2.mk" clean
