.PHONY: clean All

All:
	@echo "----------Building project:[ 11_1 - Debug ]----------"
	@cd "11_1" && $(MAKE) -f  "11_1.mk"
clean:
	@echo "----------Cleaning project:[ 11_1 - Debug ]----------"
	@cd "11_1" && $(MAKE) -f  "11_1.mk" clean
