.PHONY: clean All

All:
	@echo "----------Building project:[ 11_2 - Debug ]----------"
	@cd "11_2" && $(MAKE) -f  "11_2.mk"
clean:
	@echo "----------Cleaning project:[ 11_2 - Debug ]----------"
	@cd "11_2" && $(MAKE) -f  "11_2.mk" clean
