.PHONY: clean All

All:
	@echo "----------Building project:[ 08_1 - Debug ]----------"
	@cd "08_1" && $(MAKE) -f  "08_1.mk"
clean:
	@echo "----------Cleaning project:[ 08_1 - Debug ]----------"
	@cd "08_1" && $(MAKE) -f  "08_1.mk" clean
