.PHONY: clean All

All:
	@echo "----------Building project:[ 08_2 - Debug ]----------"
	@cd "08_2" && $(MAKE) -f  "08_2.mk"
clean:
	@echo "----------Cleaning project:[ 08_2 - Debug ]----------"
	@cd "08_2" && $(MAKE) -f  "08_2.mk" clean
