.PHONY: clean All

All:
	@echo "----------Building project:[ uebung1_5 - Debug ]----------"
	@cd "uebung1_5" && $(MAKE) -f  "uebung1_5.mk"
clean:
	@echo "----------Cleaning project:[ uebung1_5 - Debug ]----------"
	@cd "uebung1_5" && $(MAKE) -f  "uebung1_5.mk" clean
