.PHONY: clean All

All:
	@echo "----------Building project:[ uebung1 - Debug ]----------"
	@cd "uebung1" && $(MAKE) -f  "uebung1.mk"
clean:
	@echo "----------Cleaning project:[ uebung1 - Debug ]----------"
	@cd "uebung1" && $(MAKE) -f  "uebung1.mk" clean
