.PHONY: clean All

All:
	@echo "----------Building project:[ 05_1 - Debug ]----------"
	@cd "05_1" && $(MAKE) -f  "05_1.mk"
clean:
	@echo "----------Cleaning project:[ 05_1 - Debug ]----------"
	@cd "05_1" && $(MAKE) -f  "05_1.mk" clean
