.PHONY: clean All

All:
	@echo "----------Building project:[ 05_2_v2 - Debug ]----------"
	@cd "05_2_v2" && $(MAKE) -f  "05_2_v2.mk"
clean:
	@echo "----------Cleaning project:[ 05_2_v2 - Debug ]----------"
	@cd "05_2_v2" && $(MAKE) -f  "05_2_v2.mk" clean
